package core

import "github.com/hectorvent/cloudstack/internal/core/common"

func initCatalog() *common.Catalog {
	return common.NewCatalog([]*common.ServiceDescriptor{
		{
			ExternalKey:      "dynamodb",
			ConfigKey:        "dynamodb",
			Enabled:          true,
			TargetPrefixes:   []string{"DynamoDB_20120810.", "DynamoDBStreams_20120810."},
			CredentialScopes: []string{"dynamodb"},
			DefaultProtocol:  common.ProtocolJSON,
		},
		{
			ExternalKey:     "sqs",
			ConfigKey:       "sqs",
			Enabled:         true,
			TargetPrefixes:  []string{"AmazonSQS."},
			CredentialScopes: []string{"sqs"},
			DefaultProtocol: common.ProtocolQUERY,
		},
		{
			ExternalKey:     "sns",
			ConfigKey:       "sns",
			Enabled:         true,
			TargetPrefixes:  []string{"SNS_20100331."},
			CredentialScopes: []string{"sns"},
			DefaultProtocol: common.ProtocolQUERY,
		},
		{
			ExternalKey:     "iam",
			ConfigKey:       "iam",
			Enabled:         true,
			CredentialScopes: []string{"iam"},
			DefaultProtocol: common.ProtocolQUERY,
		},
		{
			ExternalKey:     "sts",
			ConfigKey:       "sts",
			Enabled:         true,
			CredentialScopes: []string{"sts"},
			DefaultProtocol: common.ProtocolQUERY,
		},
		{
			ExternalKey:     "cognito-idp",
			ConfigKey:       "cognito",
			Enabled:         true,
			TargetPrefixes:  []string{"AWSCognitoIdentityProviderService."},
			CredentialScopes: []string{"cognito-idp"},
			DefaultProtocol: common.ProtocolJSON,
		},
		{
			ExternalKey:      "lambda",
			ConfigKey:        "lambda",
			Enabled:          true,
			CredentialScopes: []string{"lambda"},
			DefaultProtocol:  common.ProtocolRESTJSON,
		},
		{
			ExternalKey:      "events",
			ConfigKey:        "eventbridge",
			Enabled:          true,
			TargetPrefixes:   []string{"AWSEvents."},
			CredentialScopes: []string{"events"},
			DefaultProtocol:  common.ProtocolJSON,
		},
		{
			ExternalKey:      "kinesis",
			ConfigKey:        "kinesis",
			Enabled:          true,
			TargetPrefixes:   []string{"Kinesis_20131202."},
			CredentialScopes: []string{"kinesis"},
			DefaultProtocol:  common.ProtocolJSON,
		},
		{
			ExternalKey:      "acm",
			ConfigKey:        "acm",
			Enabled:          true,
			TargetPrefixes:   []string{"CertificateManager."},
			CredentialScopes: []string{"acm"},
			DefaultProtocol:  common.ProtocolJSON,
		},
		{
			ExternalKey:      "apigatewayv2",
			ConfigKey:        "apigatewayv2",
			Enabled:          true,
			CredentialScopes: []string{"apigateway"},
			DefaultProtocol:  common.ProtocolJSON,
		},
		{
			ExternalKey:      "appconfig",
			ConfigKey:        "appconfig",
			Enabled:          true,
			CredentialScopes: []string{"appconfig"},
			DefaultProtocol:  common.ProtocolJSON,
		},
		{
			ExternalKey:      "appsync",
			ConfigKey:        "appsync",
			Enabled:          true,
			CredentialScopes: []string{"appsync"},
			DefaultProtocol:  common.ProtocolJSON,
		},
		{
			ExternalKey:      "athena",
			ConfigKey:        "athena",
			Enabled:          true,
			TargetPrefixes:   []string{"AmazonAthena."},
			CredentialScopes: []string{"athena"},
			DefaultProtocol:  common.ProtocolJSON,
		},
		{
			ExternalKey:      "autoscaling",
			ConfigKey:        "autoscaling",
			Enabled:          true,
			CredentialScopes: []string{"autoscaling"},
			DefaultProtocol:  common.ProtocolQUERY,
		},
		{
			ExternalKey:      "backup",
			ConfigKey:        "backup",
			Enabled:          true,
			CredentialScopes: []string{"backup"},
			DefaultProtocol:  common.ProtocolJSON,
		},
		{
			ExternalKey:      "bcmdataexports",
			ConfigKey:        "bcmdataexports",
			Enabled:          true,
			TargetPrefixes:   []string{"BillingAndCostManagementDataExports."},
			CredentialScopes: []string{"bcm-data-exports"},
			DefaultProtocol:  common.ProtocolJSON,
		},
		{
			ExternalKey:      "bedrock-runtime",
			ConfigKey:        "bedrock-runtime",
			Enabled:          true,
			CredentialScopes: []string{"bedrock"},
			DefaultProtocol:  common.ProtocolRESTJSON,
		},
		{
			ExternalKey:      "ce",
			ConfigKey:        "ce",
			Enabled:          true,
			TargetPrefixes:   []string{"AWSInsightsIndexService."},
			CredentialScopes: []string{"ce"},
			DefaultProtocol:  common.ProtocolJSON,
		},
		{
			ExternalKey:      "cloudformation",
			ConfigKey:        "cloudformation",
			Enabled:          true,
			CredentialScopes: []string{"cloudformation"},
			DefaultProtocol:  common.ProtocolQUERY,
		},
		{
			ExternalKey:      "cloudfront",
			ConfigKey:        "cloudfront",
			Enabled:          true,
			CredentialScopes: []string{"cloudfront"},
			DefaultProtocol:  common.ProtocolRESTXML,
		},
		{
			ExternalKey:      "monitoring",
			ConfigKey:        "cloudwatch",
			Enabled:          true,
			CredentialScopes: []string{"monitoring"},
			DefaultProtocol:  common.ProtocolQUERY,
		},
		{
			ExternalKey:      "codebuild",
			ConfigKey:        "codebuild",
			Enabled:          true,
			TargetPrefixes:   []string{"CodeBuild_20161006."},
			CredentialScopes: []string{"codebuild"},
			DefaultProtocol:  common.ProtocolJSON,
		},
		{
			ExternalKey:      "codedeploy",
			ConfigKey:        "codedeploy",
			Enabled:          true,
			TargetPrefixes:   []string{"CodeDeploy_20141006."},
			CredentialScopes: []string{"codedeploy"},
			DefaultProtocol:  common.ProtocolJSON,
		},
		{
			ExternalKey:      "config",
			ConfigKey:        "config",
			Enabled:          true,
			TargetPrefixes:   []string{"StarlingDoveService."},
			CredentialScopes: []string{"config"},
			DefaultProtocol:  common.ProtocolJSON,
		},
		{
			ExternalKey:      "cur",
			ConfigKey:        "cur",
			Enabled:          true,
			TargetPrefixes:   []string{"AWSOrigamiServiceGatewayService."},
			CredentialScopes: []string{"cur"},
			DefaultProtocol:  common.ProtocolJSON,
		},
		{
			ExternalKey:      "ec2",
			ConfigKey:        "ec2",
			Enabled:          true,
			CredentialScopes: []string{"ec2"},
			DefaultProtocol:  common.ProtocolQUERY,
		},
		{
			ExternalKey:      "ecr",
			ConfigKey:        "ecr",
			Enabled:          true,
			TargetPrefixes:   []string{"AmazonEC2ContainerRegistry_V20150921."},
			CredentialScopes: []string{"ecr"},
			DefaultProtocol:  common.ProtocolJSON,
		},
		{
			ExternalKey:      "ecs",
			ConfigKey:        "ecs",
			Enabled:          true,
			TargetPrefixes:   []string{"AmazonEC2ContainerServiceV20141113."},
			CredentialScopes: []string{"ecs"},
			DefaultProtocol:  common.ProtocolJSON,
		},
		{
			ExternalKey:      "eks",
			ConfigKey:        "eks",
			Enabled:          true,
			CredentialScopes: []string{"eks"},
			DefaultProtocol:  common.ProtocolJSON,
		},
		{
			ExternalKey:      "elasticache",
			ConfigKey:        "elasticache",
			Enabled:          true,
			CredentialScopes: []string{"elasticache"},
			DefaultProtocol:  common.ProtocolQUERY,
		},
		{
			ExternalKey:      "elbv2",
			ConfigKey:        "elbv2",
			Enabled:          true,
			TargetPrefixes:   []string{"ElasticLoadBalancingV2."},
			CredentialScopes: []string{"elasticloadbalancing"},
			DefaultProtocol:  common.ProtocolQUERY,
		},
		{
			ExternalKey:      "firehose",
			ConfigKey:        "firehose",
			Enabled:          true,
			TargetPrefixes:   []string{"Firehose_20150804."},
			CredentialScopes: []string{"firehose"},
			DefaultProtocol:  common.ProtocolJSON,
		},
		{
			ExternalKey:      "glue",
			ConfigKey:        "glue",
			Enabled:          true,
			TargetPrefixes:   []string{"AWSGlue."},
			CredentialScopes: []string{"glue"},
			DefaultProtocol:  common.ProtocolJSON,
		},
		{
			ExternalKey:      "kms",
			ConfigKey:        "kms",
			Enabled:          true,
			TargetPrefixes:   []string{"TrentService."},
			CredentialScopes: []string{"kms"},
			DefaultProtocol:  common.ProtocolJSON,
		},
		{
			ExternalKey:      "msk",
			ConfigKey:        "msk",
			Enabled:          true,
			TargetPrefixes:   []string{"AmazonMSK."},
			CredentialScopes: []string{"kafka"},
			DefaultProtocol:  common.ProtocolJSON,
		},
		{
			ExternalKey:      "neptune",
			ConfigKey:        "neptune",
			Enabled:          true,
			CredentialScopes: []string{"neptune-db"},
			DefaultProtocol:  common.ProtocolQUERY,
		},
		{
			ExternalKey:      "opensearch",
			ConfigKey:        "opensearch",
			Enabled:          true,
			CredentialScopes: []string{"es"},
			DefaultProtocol:  common.ProtocolRESTJSON,
		},
		{
			ExternalKey:      "pipes",
			ConfigKey:        "pipes",
			Enabled:          true,
			TargetPrefixes:   []string{"PipeService."},
			CredentialScopes: []string{"pipes"},
			DefaultProtocol:  common.ProtocolJSON,
		},
		{
			ExternalKey:      "pricing",
			ConfigKey:        "pricing",
			Enabled:          true,
			TargetPrefixes:   []string{"AWSPriceListService."},
			CredentialScopes: []string{"pricing"},
			DefaultProtocol:  common.ProtocolJSON,
		},
		{
			ExternalKey:      "rds",
			ConfigKey:        "rds",
			Enabled:          true,
			TargetPrefixes:   []string{"AmazonRDS."},
			CredentialScopes: []string{"rds"},
			DefaultProtocol:  common.ProtocolQUERY,
		},
		{
			ExternalKey:      "resourcegroupstagging",
			ConfigKey:        "resourcegroupstagging",
			Enabled:          true,
			TargetPrefixes:   []string{"ResourceGroupsTaggingAPI_20170126."},
			CredentialScopes: []string{"tagging"},
			DefaultProtocol:  common.ProtocolJSON,
		},
		{
			ExternalKey:      "route53",
			ConfigKey:        "route53",
			Enabled:          true,
			CredentialScopes: []string{"route53"},
			DefaultProtocol:  common.ProtocolRESTXML,
		},
		{
			ExternalKey:      "scheduler",
			ConfigKey:        "scheduler",
			Enabled:          true,
			TargetPrefixes:   []string{"AmazonScheduler."},
			CredentialScopes: []string{"scheduler"},
			DefaultProtocol:  common.ProtocolJSON,
		},
		{
			ExternalKey:      "secretsmanager",
			ConfigKey:        "secretsmanager",
			Enabled:          true,
			TargetPrefixes:   []string{"secretsmanager."},
			CredentialScopes: []string{"secretsmanager"},
			DefaultProtocol:  common.ProtocolJSON,
		},
		{
			ExternalKey:      "email",
			ConfigKey:        "ses",
			Enabled:          true,
			CredentialScopes: []string{"ses"},
			DefaultProtocol:  common.ProtocolQUERY,
		},
		{
			ExternalKey:      "ssm",
			ConfigKey:        "ssm",
			Enabled:          true,
			TargetPrefixes:   []string{"AmazonSSM."},
			CredentialScopes: []string{"ssm"},
			DefaultProtocol:  common.ProtocolJSON,
		},
		{
			ExternalKey:      "stepfunctions",
			ConfigKey:        "stepfunctions",
			Enabled:          true,
			TargetPrefixes:   []string{"AWSStepFunctions."},
			CredentialScopes: []string{"states"},
			DefaultProtocol:  common.ProtocolJSON,
		},
		{
			ExternalKey:      "textract",
			ConfigKey:        "textract",
			Enabled:          true,
			TargetPrefixes:   []string{"Textract."},
			CredentialScopes: []string{"textract"},
			DefaultProtocol:  common.ProtocolJSON,
		},
		{
			ExternalKey:      "transcribe",
			ConfigKey:        "transcribe",
			Enabled:          true,
			TargetPrefixes:   []string{"Transcribe."},
			CredentialScopes: []string{"transcribe"},
			DefaultProtocol:  common.ProtocolJSON,
		},
		{
			ExternalKey:      "transfer",
			ConfigKey:        "transfer",
			Enabled:          true,
			TargetPrefixes:   []string{"TransferService."},
			CredentialScopes: []string{"transfer"},
			DefaultProtocol:  common.ProtocolJSON,
		},
	})
}
